# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2'

# Server
gem 'puma', '~> 5.5.2'

# Messaging via GCP Pub/Sub
gem 'cloudenvoy', path: '../../'

# Active record adapter
gem 'sqlite3'
