# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Web framework
gem 'sinatra'

# Server
gem 'puma', '~> 5.5.2'

# Support rake tasks
gem 'rake'

# Pub/sub via cloudenvoy
gem 'cloudenvoy', path: '../../'
