# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.5'

# Web framework
gem 'sinatra'

# Support rake tasks
gem 'rake'

# Pub/sub via cloudenvoy
gem 'cloudenvoy', path: '../../'
